# Generated by Django 5.2.17 on 2026-08-22 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='website',
            name='a11y_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='last_scanned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='perf_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='seo_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scanning', 'Scanning'), ('error', 'Error')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='website',
            name='total_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['user', 'status'], name='websites_we_user_id_19b296_idx'),
        ),
    ]
