# Generated by Django 5.2.17 on 2026-08-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('website_name', models.CharField(max_length=255)),
                ('website_url', models.URLField()),
                ('seo_score', models.IntegerField(default=0)),
                ('perf_score', models.IntegerField(default=0)),
                ('a11y_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('fixes_applied', models.IntegerField(default=0)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('pdf_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scanners.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
