# Generated by Django 5.2.17 on 2026-08-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('seo', 'SEO'), ('performance', 'Performance'), ('accessibility', 'Accessibility')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='scanners.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scan', 'result_type')},
            },
        ),
    ]
