# Generated by Django 5.2.17 on 2026-08-22 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, default='mistral', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='scanners.scanjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('issue_type', models.CharField(choices=[('seo', 'SEO'), ('performance', 'Performance'), ('accessibility', 'Accessibility'), ('general', 'General')], default='general', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fix_code', models.TextField(blank=True, default='')),
                ('affected_file', models.CharField(blank=True, default='', max_length=255)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('model_used', models.CharField(default='mistral', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_fixes', to='scanners.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
