"use client"

import React, { useState } from 'react'
import { Camera, ArrowLeftRight, CheckCircle2 } from 'lucide-react'

interface VisualDiffProps {
  beforeLabel?: string
  afterLabel?: string
}

export function VisualDiffViewer({
  beforeLabel = 'Before AI Fix (Uncompressed Image & Missing Meta)',
  afterLabel = 'After AI Fix (Optimized WebP + WCAG AA Contrast)',
}: VisualDiffProps) {
  const [sliderPosition, setSliderPosition] = useState(50)

  return (
    <div className="p-6 rounded-2xl bg-card shadow-sm space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Camera className="w-5 h-5 text-foreground" />
          <h3 className="text-base font-bold text-foreground">Playwright Visual Diff Report</h3>
        </div>
        <span className="text-xs font-mono text-muted-foreground px-2.5 py-1 rounded bg-muted">
          Viewport: 1440x900 (Desktop)
        </span>
      </div>

      <p className="text-xs text-muted-foreground">
        Interactive slider comparing original site render vs AI-patched render generated by Playwright headless browser.
      </p>

      {/* Comparison Slider Frame */}
      <div
        className="relative w-full h-[340px] rounded-xl overflow-hidden bg-muted select-none group cursor-ew-resize"
        onMouseMove={(e) => {
          const rect = e.currentTarget.getBoundingClientRect()
          const x = Math.max(0, Math.min(e.clientX - rect.left, rect.width))
          setSliderPosition((x / rect.width) * 100)
        }}
      >
        {/* AFTER Image (Background) */}
        <div className="absolute inset-0 bg-muted/60 p-6 flex flex-col justify-between">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-background text-foreground text-xs font-bold w-fit shadow-sm">
            <CheckCircle2 className="w-3.5 h-3.5" /> {afterLabel}
          </div>
          <div className="p-6 bg-card rounded-xl text-foreground max-w-md font-sans shadow-sm">
            <div className="h-6 w-3/4 bg-primary/20 rounded mb-3" />
            <div className="h-4 w-full bg-muted rounded mb-2" />
            <div className="h-4 w-5/6 bg-muted rounded" />
            <span className="inline-block mt-4 text-[10px] text-muted-foreground font-mono">
              ✓ LCP latency reduced from 3.8s → 1.2s | Contrast ratio 6.4:1
            </span>
          </div>
        </div>

        {/* BEFORE Image (Clipped Overlay) */}
        <div
          className="absolute inset-y-0 left-0 bg-muted p-6 flex flex-col justify-between overflow-hidden border-r border-primary/40"
          style={{ width: `${sliderPosition}%` }}
        >
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-background text-muted-foreground text-xs font-bold w-fit shadow-sm whitespace-nowrap">
            ⚠️ {beforeLabel}
          </div>
          <div className="p-6 bg-card rounded-xl text-muted-foreground max-w-md font-sans min-w-[320px] shadow-sm">
            <div className="h-6 w-3/4 bg-muted-foreground/20 rounded mb-3" />
            <div className="h-4 w-full bg-muted rounded mb-2" />
            <div className="h-4 w-5/6 bg-muted rounded" />
            <span className="inline-block mt-4 text-[10px] text-muted-foreground font-mono">
              ❌ Uncompressed 4MB Hero PNG | Low Contrast #718096
            </span>
          </div>
        </div>

        {/* Divider Handle */}
        <div
          className="absolute top-0 bottom-0 w-1 bg-primary cursor-ew-resize shadow-lg flex items-center justify-center"
          style={{ left: `${sliderPosition}%` }}
        >
          <div className="p-1.5 rounded-full bg-primary text-primary-foreground shadow-md">
            <ArrowLeftRight className="w-4 h-4" />
          </div>
        </div>
      </div>
    </div>
  )
}
