"use client"

import React, { useState } from 'react'
import { AppSidebar } from "@/components/app-sidebar"
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb"
import { Separator } from "@/components/ui/separator"
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AiFixCard } from '@/components/ai/AiFixCard'
import { AiChatPanel } from '@/components/ai/AiChatPanel'
import { useAiStore } from '@/store/aiStore'
import { Sparkle, Cpu, Wrench, Robot, ShieldCheck } from '@phosphor-icons/react'

export default function FixesPage() {
  const { fixes, selectedModel, setSelectedModel } = useAiStore()
  const [filterSeverity, setFilterSeverity] = useState<string>('all')

  const filteredFixes = fixes.filter(
    (f) => filterSeverity === 'all' || f.severity === filterSeverity
  )

  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center justify-between px-4">
          <div className="flex items-center gap-2">
            <SidebarTrigger className="-ml-1" />
            <Separator orientation="vertical" className="mr-2 data-vertical:h-4" />
            <Breadcrumb>
              <BreadcrumbList>
                <BreadcrumbItem>
                  <BreadcrumbLink href="/dashboard">Fixora AI</BreadcrumbLink>
                </BreadcrumbItem>
                <BreadcrumbSeparator />
                <BreadcrumbItem>
                  <BreadcrumbPage>AI Fix Center</BreadcrumbPage>
                </BreadcrumbItem>
              </BreadcrumbList>
            </Breadcrumb>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-mono text-muted-foreground hidden sm:inline">Local Model:</span>
            <select
              value={selectedModel}
              onChange={(e) => setSelectedModel(e.target.value as any)}
              className="text-xs bg-muted rounded-xl px-3 py-1.5 font-mono font-bold text-foreground focus:ring-2 focus:ring-primary shadow-sm"
            >
              <option value="mistral">Mistral 7B (Fast)</option>
              <option value="llama3.1:8b">Llama 3.1 8B (Deep Fixes)</option>
            </select>
          </div>
        </header>

        <div className="flex flex-1 flex-col gap-6 p-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-2xl font-extrabold tracking-tight text-foreground flex items-center gap-2">
                <Wrench className="w-6 h-6 text-foreground" /> AI Code Patch Generator
              </h1>
              <p className="text-xs text-muted-foreground">
                One-click AI patch suggestions generated by local Ollama LLMs with 0 API costs.
              </p>
            </div>

            <div className="flex items-center gap-1.5 text-xs bg-muted p-1.5 rounded-xl">
              {['all', 'critical', 'high', 'medium'].map((sev) => (
                <button
                  key={sev}
                  onClick={() => setFilterSeverity(sev)}
                  className={`px-3 py-1 rounded-lg font-bold font-mono capitalize transition-all ${
                    filterSeverity === sev
                      ? 'bg-primary text-primary-foreground shadow-sm'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  {sev}
                </button>
              ))}
            </div>
          </div>

          {/* Main Grid: Left Fix List, Right Chat Assistant */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-4">
              <h3 className="text-sm font-bold text-foreground">Available Code Patches ({filteredFixes.length})</h3>
              {filteredFixes.map((fix) => (
                <AiFixCard key={fix.id} fix={fix} />
              ))}
            </div>

            <div>
              <AiChatPanel />
            </div>
          </div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}
