import type { Website } from '../types/website';
import type { ScanJob } from '../types/scanner';
import type { AiFix } from '../types/ai';
import type { A11yIssue } from '../types/accessibility';
import type { CoreWebVital } from '../types/performance';
import type { ReportSummary } from '../types/report';

export const INITIAL_WEBSITES: Website[] = [
  {
    id: 'web-1',
    name: 'Fixora SaaS App',
    url: 'https://fixora.ai',
    status: 'active',
    owner: 'Engineering Team',
    created_at: '2025-01-15T10:00:00Z',
    last_scanned: '2025-02-01T14:30:00Z',
    seo_score: 92,
    perf_score: 88,
    a11y_score: 96,
    overall_score: 92,
    total_issues: 4,
    tech_stack: ['Next.js 14', 'React 19', 'Tailwind CSS'],
  },
  {
    id: 'web-2',
    name: 'Acme E-Commerce Store',
    url: 'https://store.acme-corp.com',
    status: 'active',
    owner: 'Product Ops',
    created_at: '2025-01-18T12:00:00Z',
    last_scanned: '2025-02-01T09:15:00Z',
    seo_score: 74,
    perf_score: 61,
    a11y_score: 83,
    overall_score: 73,
    total_issues: 18,
    tech_stack: ['Shopify', 'Liquid', 'Google Tag Manager'],
  },
  {
    id: 'web-3',
    name: 'DevDocs Knowledge Portal',
    url: 'https://docs.fixora.ai',
    status: 'active',
    owner: 'Tech Writing',
    created_at: '2025-01-20T08:30:00Z',
    last_scanned: '2025-01-31T18:00:00Z',
    seo_score: 98,
    perf_score: 95,
    a11y_score: 99,
    overall_score: 97,
    total_issues: 1,
    tech_stack: ['Starlight', 'Astro', 'Tailwind CSS'],
  },
  {
    id: 'web-4',
    name: 'Marketing Campaign Landing',
    url: 'https://launch.fixora.ai',
    status: 'scanning',
    owner: 'Growth Team',
    created_at: '2025-01-28T16:20:00Z',
    last_scanned: 'Just now',
    seo_score: 81,
    perf_score: 69,
    a11y_score: 77,
    overall_score: 76,
    total_issues: 11,
    tech_stack: ['Vite', 'React 18', 'Framer Motion'],
  },
];

export const INITIAL_AI_FIXES: AiFix[] = [
  {
    id: 'fix-101',
    issue_type: 'seo',
    severity: 'critical',
    title: 'Missing Meta Description & OpenGraph Tags',
    description: 'The root page is missing `<meta name="description">` causing reduced search visibility and unformatted social media link previews.',
    fix_code: `<head>\n  <title>Fixora AI - AI Powered Website Fixer</title>\n  <meta name="description" content="Fixora AI scans your website for SEO, performance, and accessibility flaws and fixes them instantly with free local Ollama AI models." />\n  <meta property="og:title" content="Fixora AI" />\n  <meta property="og:description" content="Instant AI-powered site analysis and code patches." />\n</head>`,
    affected_file: 'src/app/layout.tsx',
    line_number: 14,
    model_used: 'mistral',
    confidence: 0.98,
    applied: false,
  },
  {
    id: 'fix-102',
    issue_type: 'performance',
    severity: 'high',
    title: 'Unoptimized Heavy Hero PNG Image (3.4 MB)',
    description: 'Hero background image is served as uncompressed PNG. Converting to WebP/AVIF format with Next.js <Image /> component reduces payload by 84%.',
    fix_code: `// Replace original <img> tag:\n// <img src="/hero.png" width="1920" height="1080" />\n\nimport Image from 'next/image';\nimport heroWebp from '@/public/hero.webp';\n\n<Image\n  src={heroWebp}\n  alt="Fixora AI Dashboard Preview"\n  priority\n  placeholder="blur"\n  quality={85}\n/>`,
    affected_file: 'src/components/HeroBanner.tsx',
    line_number: 42,
    model_used: 'llama3.1:8b',
    confidence: 0.95,
    applied: false,
  },
  {
    id: 'fix-103',
    issue_type: 'accessibility',
    severity: 'critical',
    title: 'Interactive Buttons Lack Accessible Names (aria-label)',
    description: 'Icon-only buttons in navbar trigger WCAG 2.1 A failures because screen readers cannot announce their destination or function.',
    fix_code: `<!-- Before -->\n<button className="p-2"><SearchIcon /></button>\n\n<!-- Fixed Code -->\n<button className="p-2" aria-label="Search website content">\n  <SearchIcon aria-hidden="true" />\n</button>`,
    affected_file: 'src/components/layout/Header.tsx',
    line_number: 28,
    model_used: 'mistral',
    confidence: 0.99,
    applied: false,
  },
  {
    id: 'fix-104',
    issue_type: 'performance',
    severity: 'medium',
    title: 'Render-Blocking Google Font Stylesheet',
    description: 'Google Fonts CSS is loaded synchronously in the `<head>` blocking initial DOM render by ~340ms.',
    fix_code: `<link rel="preconnect" href="https://fonts.googleapis.com" />\n<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" media="print" onload="this.media='all'" />`,
    affected_file: 'src/app/layout.tsx',
    line_number: 8,
    model_used: 'llama3.1:8b',
    confidence: 0.91,
    applied: false,
  },
];

export const INITIAL_A11Y_ISSUES: A11yIssue[] = [
  {
    id: 'a11y-1',
    code: 'color-contrast',
    wcag_level: 'AA',
    impact: 'critical',
    help: 'Elements must have sufficient color contrast ratio (minimum 4.5:1)',
    description: 'Text element `#718096` on background `#EDF2F7` has contrast ratio of 3.2:1. Fails WCAG AA standard for normal text.',
    selector: 'div.hero-banner > p.subtitle',
    html_snippet: '<p className="text-gray-400 text-sm">Analyze and fix your code instantly</p>',
    suggested_fix: 'Change text class to `text-gray-700` or `#4A5568` to achieve a contrast ratio of 5.8:1.',
  },
  {
    id: 'a11y-2',
    code: 'image-alt',
    wcag_level: 'A',
    impact: 'serious',
    help: 'Images must have non-empty alt text attributes',
    description: 'Informative logo SVG image lacks an `alt` attribute or `role="img"` label for assistative technology users.',
    selector: 'nav.navbar img.brand-logo',
    html_snippet: '<img src="/logo.svg" className="h-8" />',
    suggested_fix: 'Add `alt="Fixora AI Brand Logo"` to the image element.',
  },
  {
    id: 'a11y-3',
    code: 'label-title-only',
    wcag_level: 'A',
    impact: 'moderate',
    help: 'Form input elements must have associated visible label elements',
    description: 'Email search input relies solely on placeholder text which disappears when user types.',
    selector: 'form.newsletter-form input#email-input',
    html_snippet: '<input id="email-input" type="email" placeholder="Enter work email" />',
    suggested_fix: 'Add `<label htmlFor="email-input">Work Email</label>` or explicit `aria-label="Work Email"`.',
  },
];

export const CORE_WEB_VITALS_DATA: CoreWebVital[] = [
  { metric: 'LCP', name: 'Largest Contentful Paint', value: 1.8, unit: 's', status: 'good', benchmark: '< 2.5s' },
  { metric: 'FID', name: 'First Input Delay', value: 14, unit: 'ms', status: 'good', benchmark: '< 100ms' },
  { metric: 'CLS', name: 'Cumulative Layout Shift', value: 0.04, unit: 'score', status: 'good', benchmark: '< 0.1' },
  { metric: 'FCP', name: 'First Contentful Paint', value: 0.9, unit: 's', status: 'good', benchmark: '< 1.8s' },
  { metric: 'TTFB', name: 'Time to First Byte', value: 210, unit: 'ms', status: 'good', benchmark: '< 800ms' },
  { metric: 'INP', name: 'Interaction to Next Paint', value: 72, unit: 'ms', status: 'good', benchmark: '< 200ms' },
];

export const MOCK_REPORTS: ReportSummary[] = [
  {
    id: 'rep-1',
    website_id: 'web-1',
    website_name: 'Fixora SaaS App',
    website_url: 'https://fixora.ai',
    created_at: '2025-02-01T14:30:00Z',
    seo_score: 92,
    perf_score: 88,
    a11y_score: 96,
    overall_score: 92,
    total_issues: 4,
    fixes_applied: 3,
    summary_text: 'Fixora SaaS App scored 92/100 overall. Core Web Vitals are within healthy range. 3 AI fixes were automatically applied.',
  },
  {
    id: 'rep-2',
    website_id: 'web-2',
    website_name: 'Acme E-Commerce Store',
    website_url: 'https://store.acme-corp.com',
    created_at: '2025-02-01T09:15:00Z',
    seo_score: 74,
    perf_score: 61,
    a11y_score: 83,
    overall_score: 73,
    total_issues: 18,
    fixes_applied: 5,
    summary_text: 'Acme E-Commerce Store needs attention on LCP image payload and WCAG AA color contrast ratios across product listing pages.',
  },
];
